// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Accordion: typeof import('./src/components/ui/Accordion.vue')['default']
    AdminOverviewBox: typeof import('./src/components/admin/AdminOverviewBox.vue')['default']
    DarkMode: typeof import('./src/components/ui/DarkMode.vue')['default']
    DashboardSkeleton: typeof import('./src/components/skeleton/dashboardSkeleton.vue')['default']
    DataTable: typeof import('./src/components/ui/DataTable.vue')['default']
    Errors: typeof import('./src/components/ui/Errors.vue')['default']
    LoadingPage: typeof import('./src/components/LoadingPage.vue')['default']
    MobileNavigationDrawer: typeof import('./src/components/ui/MobileNavigationDrawer.vue')['default']
    MultiSelect: typeof import('./src/components/ui/MultiSelect.vue')['default']
    Navbar: typeof import('./src/components/navbar.vue')['default']
    NavigationDrawer: typeof import('./src/components/ui/NavigationDrawer.vue')['default']
    Otp: typeof import('./src/components/ui/Otp.vue')['default']
    OverviewBox: typeof import('./src/components/OverviewBox.vue')['default']
    ProfileAddress: typeof import('./src/components/profile/ProfileAddress.vue')['default']
    ProfileCompleteInformation: typeof import('./src/components/profile/ProfileCompleteInformation.vue')['default']
    ProfileInfo: typeof import('./src/components/profile/ProfileInfo.vue')['default']
    ProfileUploadDocument: typeof import('./src/components/profile/ProfileUploadDocument.vue')['default']
    RButton: typeof import('./src/components/ui/RButton.vue')['default']
    RequestCard: typeof import('./src/components/request/RequestCard.vue')['default']
    RequestCardSkeleton: typeof import('./src/components/skeleton/requestCardSkeleton.vue')['default']
    RInput: typeof import('./src/components/ui/RInput.vue')['default']
    RModal: typeof import('./src/components/RModal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RPrgoressBar: typeof import('./src/components/ui/RPrgoressBar.vue')['default']
    RStepper: typeof import('./src/components/ui/RStepper.vue')['default']
    TableSkeleton: typeof import('./src/components/skeleton/tableSkeleton.vue')['default']
    UploadBox: typeof import('./src/components/ui/UploadBox.vue')['default']
  }
}
